---
- name: restart bind_exporter
  service:
    name: bind_exporter
    state: restarted
  tags: [ prometheus, bind_exporter ]

- name: systemd reload
  systemd:
    daemon_reload: true
  tags: [ prometheus, bind_exporter ]
...
